services:
  bind:
    image: ubuntu/bind9:9.20-26.04_stable
    restart: always
    networks:
      default:
        ipv4_address: 192.168.53.10
    user: bind
    ports:
      - $IP:53:53
      - $IP:53:53/udp
      - $IP:853:853
    volumes:
      - ./bind.conf:/etc/bind/named.conf:ro
      - ./certs:/etc/bind/tls:ro
      - ./data:/etc/bind
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
  dnsmasq:
    image: dockurr/dnsmasq
    restart: always
    networks:
      default:
        ipv4_address: 192.168.53.20
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
  certbot:
    image: certbot/dns-cloudflare:latest
    restart: always
    networks:
      default:
        ipv4_address: 192.168.53.30
    environment:
      EMAIL: ${EMAIL}
      DOMAIN: ${DOMAIN}
      CF_API_TOKEN: ${CF_API_TOKEN}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/cache:/var/lib/letsencrypt
      - ./certs:/bind-certs
    entrypoint:
      - /bin/sh
      - -c
      - |
        cleanup() {
            echo "Received termination signal. Exiting..."
            exit 0
        }

        trap cleanup TERM INT

        echo "dns_cloudflare_api_token = $CF_API_TOKEN" > /cloudflare.ini
        chmod 600 /cloudflare.ini

        DEPLOY_HOOK='cp -L /etc/letsencrypt/live/'"$DOMAIN"'/fullchain.pem /bind-certs/fullchain.pem && \
        cp -L /etc/letsencrypt/live/'"$DOMAIN"'/privkey.pem /bind-certs/privkey.pem && \
        chmod 644 /bind-certs/*.pem'

        if [ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
            certbot certonly \
                --non-interactive \
                --agree-tos \
                --email $EMAIL \
                --dns-cloudflare \
                --dns-cloudflare-credentials /cloudflare.ini \
                --dns-cloudflare-propagation-seconds 60 \
                -d "*.$DOMAIN" \
                --deploy-hook "$$DEPLOY_HOOK"
        fi

        while true; do
            certbot renew \
                --deploy-hook "$$DEPLOY_HOOK" \
                --quiet

            sleep 12h &
            wait $!
        done

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.53.0/24